apiVersion: v1
kind: Service
metadata:
  name: assign-7
spec:
  selector:
      pod: assign-7-pod
  ports:
    - protocol: TCP
      port: 8080       # The port, the service listens on.
      targetPort: 80   # The port, the traffic is sent to on the Pod.
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-7
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: assign-7-pod
  template:
    metadata:
      labels:
        pod: assign-7-pod
    spec:
      containers:
        - name: assign-7
          image: kaopun/softarch-assignment-7:latest
